# Generated by Django 2.2 on 2019-04-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20190423_1551'),
        ('registros_horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohoraextra',
            old_name='nome',
            new_name='motivo',
        ),
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
