# Generated by Django 2.2 on 2019-04-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
    ]
